spring:
  application:
    name: dscommerce

  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    console: >
      %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint}
      %clr(%-5p)
      %clr([%t]){cyan}
      %clr(%-50.50logger{0}){blue}
      %clr(:){yellow}
      %m%n